import{createRequire}from'node:module';import{createServer}from'node:http';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{resolve,extname}from'node:path';import assert from'node:assert/strict';import{createD1}from'./d1.mjs';import{handleAPI,sha}from'../worker/api.js';import{securityHeaders}from'../worker/index.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.SG_PLAYWRIGHT_PATH || (process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright')),root=resolve('public'),env={DB:createD1()},testKey='d'.repeat(64),data=JSON.parse(readFileSync('public/data/ipa-verified.json'));
await env.DB.prepare('INSERT INTO app_config(id,key_hash) VALUES(1,?)').bind(await sha('sg-study-deck:'+testKey)).run();
const server=createServer(async(req,res)=>{const origin=`http://127.0.0.1:${server.address().port}`,path=new URL(req.url,origin).pathname;try{if(path.startsWith('/api/')){const chunks=[];for await(const chunk of req)chunks.push(chunk);const r=await handleAPI(new Request(origin+req.url,{method:req.method,headers:{...req.headers,'CF-Connecting-IP':'browser'},...(chunks.length?{body:Buffer.concat(chunks)}:{})}),env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());return;}const file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root+'/'))throw Error('path');res.writeHead(200,{'Content-Type':{'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'}[extname(file)]||'text/plain',...securityHeaders});res.end(readFileSync(file));}catch{res.writeHead(404).end('Not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const origin=`http://127.0.0.1:${server.address().port}`;
mkdirSync('qa',{recursive:true});let browser;const passed=[],errors=[];
const pass=s=>{passed.push(s);console.log('PASS',s);};
try{
 browser=await chromium.launch({...(process.env.SG_CHROMIUM_PATH?{executablePath:process.env.SG_CHROMIUM_PATH}:{}),timeout:20000,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--in-process-gpu']});
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,permissions:['clipboard-read','clipboard-write']}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const getData=()=>page.evaluate(async()=>{const db=await import('./js/db.js');return{attempts:await db.all('attempts'),settings:await db.settings(),sync:await db.syncState(),sessions:await db.all('sessions')};});
 const instrument=()=>page.evaluate(async()=>{const{AudioEngine}=await import('./js/audio.js');for(const name of ['start','select','pause','end']){const original=AudioEngine.prototype[name];AudioEngine.prototype[name]=function(...args){window.qaEngine=this;return original.apply(this,args);};}});
 const nav=id=>page.locator(`#nav [data-view="${id}"]`).click();
 await page.goto(origin);await page.waitForSelector('[data-mode="quick"]');await page.waitForFunction(()=>navigator.serviceWorker.controller);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'qa/home-mobile.png',fullPage:true});pass('390px home, no overflow, service worker ready');await instrument();
 for(const theme of ['neon','boss','cyber']){await page.locator(`[data-action="theme"][data-theme="${theme}"]`).click();await page.locator('[data-mode="quick"]').first().click();await page.waitForSelector('.option');const stem=await page.locator('#question-stem').innerText(),q=data.questions.find(q=>q.stem===stem);assert(q);const count=(await getData()).attempts.length;await page.locator(`[data-option="${q.correctOptionId}"]`).evaluate(el=>{el.click();el.click();el.click();});await page.waitForSelector('.fx-word');assert.equal((await getData()).attempts.length,count+1);await page.screenshot({path:`qa/play-${theme}.png`,fullPage:true});await page.locator('[data-action="pause"]').click();await page.locator('[data-action="finish"]').click();await page.waitForSelector('.result-hero');await page.locator('[data-action="nav"][data-view="home"]').first().click();pass(theme+': correct effects, no duplicate taps, saved answer');}
 await nav('settings');await page.waitForSelector('#audio-input');
 function wav(hz){const rate=22050,n=rate*60,b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*2,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(Math.sin(2*Math.PI*hz*i/rate)*3000),44+i*2);return b;}
 await page.locator('#audio-input').setInputFiles([{name:'Neon test.wav',mimeType:'audio/wav',buffer:wav(220)},{name:'Boss test.wav',mimeType:'audio/wav',buffer:wav(330)}]);await page.waitForFunction(()=>document.querySelectorAll('.track').length===2);pass('multiple audio import, separate persistent blobs');
 await page.locator('[data-action="track-play"]').first().click();await page.waitForFunction(()=>window.qaEngine?.wantPlay&&qaEngine.channels[qaEngine.current].audio.currentTime>.1);await page.locator('[data-action="track-play"]').nth(1).click();await page.waitForFunction(()=>qaEngine.audit.some(x=>x.type==='crossfade'));pass('smooth GainNode crossfade');
 await page.locator('#set-sfx').fill('0.13');await page.locator('#set-sfx').dispatchEvent('input');await page.locator('#set-sfx').dispatchEvent('change');assert.equal(await page.evaluate(()=>qaEngine.settings.sfx),.13);assert.equal(await page.evaluate(()=>qaEngine.settings.bgm),.55);pass('independent BGM and SFX volume');
 await page.screenshot({path:'qa/settings-mobile.png',fullPage:true});await page.locator('#recovery-key').fill(testKey);await page.locator('[data-action="cloud-login"]').click();await page.waitForSelector('[data-action="cloud-logout"]');await page.locator('[data-action="cloud-save"]').click();await page.waitForFunction(()=>document.querySelector('#cloud-status')?.textContent==='クラウド保存済み');const saved=await getData();assert.equal(saved.sync.sentRevision,saved.sync.revision);pass('HttpOnly cookie login, upload and readback verification');
 await page.locator('[data-action="cloud-history"]').click();await page.waitForSelector('[data-action="cloud-restore"]');await page.locator('[data-action="cloud-restore"]').click();await page.waitForSelector('[data-action="confirm-restore"]');await page.locator('[data-action="confirm-restore"]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);assert.equal(await page.evaluate(async()=>{const db=await import('./js/db.js');return(await db.all('safetyCopies')).length;}),1);pass('cloud restore creates safety copy');
 await nav('home');await page.locator('[data-mode="quick"]').first().click();await page.waitForSelector('.option');await page.waitForFunction(()=>qaEngine.wantPlay);
 for(let i=0;i<10;i++){const stem=await page.locator('#question-stem').innerText(),q=data.questions.find(q=>q.stem===stem);await page.locator(`[data-option="${q.correctOptionId}"]`).click();if(i<9)await page.waitForFunction(stem=>document.querySelector('#question-stem')?.textContent!==stem,stem);}
 await page.waitForSelector('.result-hero');const fade=await page.evaluate(()=>({gain:qaEngine.channels[qaEngine.current].gain.gain.value,paused:qaEngine.channels[qaEngine.current].audio.paused,audit:qaEngine.audit.at(-1)}));assert.equal(fade.audit.seconds,2.5);assert.equal(fade.paused,false);assert(fade.gain>0);await page.waitForTimeout(2800);assert.equal(await page.evaluate(()=>qaEngine.channels[qaEngine.current].audio.paused),true);assert.equal(await page.evaluate(()=>qaEngine.channels[qaEngine.current].gain.gain.value),0);pass('BGM continues across 10 questions and fades for 2.5s');
 await page.locator('[data-action="nav"][data-view="home"]').first().click();await nav('stats');await page.waitForSelector('#stats-period');await page.screenshot({path:'qa/stats-mobile.png',fullPage:true});await page.locator('#stats-period').selectOption('week');await page.locator('#stats-period').selectOption('month');pass('day, week, month statistics');await nav('home');await page.locator('[data-mode="mock"]').click();await page.waitForFunction(()=>document.querySelector('#modal-content')?.textContent.includes('A 22問／B 0問'));await page.locator('#modal-close').click();pass('mock safely blocked until correct composition exists');
 await context.setOffline(true);await page.reload();await page.waitForSelector('[data-mode="quick"]');await page.evaluate(async()=>{const db=await import('./js/db.js'),q=(await db.all('questionCatalog'))[0],s={sessionId:'offline-100',mode:'endless',activeMs:10000,status:'complete',startedAt:new Date().toISOString()};await db.saveSession(s);for(let i=0;i<100;i++)await db.saveAnswer({attemptId:'offline-'+i,questionId:q.questionId,revision:1,sessionId:s.sessionId,answeredAt:new Date(Date.now()+i).toISOString(),selectedOptionId:'ア',correct:false,responseMs:500,topicTagsSnapshot:q.topicTags,mode:'endless'},s);});const off=await getData();await page.reload();await page.waitForSelector('[data-mode="quick"]');assert.equal((await getData()).attempts.length,off.attempts.length);pass('100 offline IndexedDB answers survive reload');await instrument();
 await nav('settings');await page.waitForSelector('.track');assert.equal(await page.locator('.track').count(),2);await page.locator('[data-action="track-play"]').first().click();await page.waitForFunction(()=>window.qaEngine?.wantPlay&&qaEngine.channels[qaEngine.current].audio.currentTime>.1);pass('audio survives reload and plays offline');
 await page.evaluate(async()=>{const {celebrate}=await import('./js/effects.js');for(const combo of [5,10,20]){celebrate('neon',combo,{effects:'high',vibration:false});if(!document.querySelector('.fx-word').textContent.includes(combo+' COMBO'))throw Error('Milestone missing');if(document.querySelectorAll('.particle').length!==55)throw Error('Milestone particles missing');}});pass('5, 10 and 20 combo special effects');
 await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(async()=>{const {celebrate}=await import('./js/effects.js');celebrate('cyber',20,{effects:'high',vibration:false});if(document.querySelector('.particle'))throw Error('Reduced motion particles');});await page.emulateMedia({reducedMotion:'no-preference'});pass('reduced motion respects system setting');
 await page.locator('[data-action="track-play"]').first().evaluate(el=>{el.click();document.querySelectorAll('[data-action="track-play"]')[1].click();el.click();});await page.waitForFunction(()=>window.qaEngine?.wantPlay&&!qaEngine.transitioning&&!qaEngine.channels[qaEngine.current].audio.paused);pass('rapid music changes resolve to continuous playback');
 await nav('home');await page.locator('[data-mode="first"]').click();await page.waitForSelector('.option');const firstStem=await page.locator('#question-stem').innerText(),firstQ=data.questions.find(q=>q.stem===firstStem),wrong=firstQ.options.find(o=>o.id!==firstQ.correctOptionId).id;await page.locator(`[data-option="${wrong}"]`).click();await page.waitForSelector('.explanation');await page.waitForTimeout(1400);assert.equal(await page.locator('#question-stem').innerText(),firstStem);await page.locator('[data-action="next"]').click();await page.waitForFunction(stem=>document.querySelector('#question-stem')?.textContent!==stem,firstStem);pass('first challenge draws unseen questions; wrong answers show explanations and wait');await page.locator('[data-action="pause"]').click();await page.locator('[data-action="finish"]').click();await page.waitForSelector('.result-hero');await nav('home');
 await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);pass('360px minimum mobile width has no horizontal overflow');
 await page.locator('[data-mode="quick"]').first().click();await page.waitForSelector('.option');const failStem=await page.locator('#question-stem').innerText(),failQ=data.questions.find(q=>q.stem===failStem);const oldCount=(await getData()).attempts.length;await page.evaluate(()=>{window.qaOriginalAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args){if(this.name==='attempts')throw new DOMException('QA capacity failure','QuotaExceededError');return qaOriginalAdd.apply(this,args);};});await page.locator(`[data-option="${failQ.correctOptionId}"]`).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('保存に失敗'));assert.equal(await page.locator('#question-stem').innerText(),failStem);assert.equal((await getData()).attempts.length,oldCount);await page.evaluate(()=>{IDBObjectStore.prototype.add=qaOriginalAdd;});await page.locator(`[data-option="${failQ.correctOptionId}"]`).click();await page.waitForFunction(n=>document.querySelector('[data-action="show-explanation"]'),oldCount);assert.equal((await getData()).attempts.length,oldCount+1);pass('failed IndexedDB transaction blocks progression; retry commits once');await page.locator('[data-action="pause"]').click();await page.locator('[data-action="finish"]').click();await page.waitForSelector('.result-hero');await nav('home');
 await page.evaluate(async()=>{const db=await import('./js/db.js'),q=(await db.all('questionCatalog'))[0],questions=[];for(let i=0;i<48;i++)questions.push({...structuredClone(q),questionId:'qa-mock-A-'+i,stem:'QA fixture A '+i});for(let i=0;i<12;i++)questions.push({...structuredClone(q),questionId:'qa-mock-B-'+i,subject:'B',stem:'QA fixture B '+i});await db.importPack({formatVersion:1,questions});});await nav('home');await page.locator('[data-mode="mock"]').click();await page.waitForSelector('.option');const mockSession=(await getData()).sessions.find(s=>s.status==='active'&&s.mode==='mock');assert.equal(mockSession.questionIds.length,60);assert.equal(mockSession.questionIds.filter(id=>id.startsWith('qa-mock-B-')).length,12);assert(Math.abs(mockSession.deadline-Date.now()-120*60000)<10000);const mockStem=await page.locator('#question-stem').innerText();await page.locator('.option').first().click();await page.waitForFunction(stem=>document.querySelector('#question-stem')?.textContent!==stem,mockStem);assert.equal(await page.locator('.explanation').count(),0);await page.locator('[data-action="pause"]').click();await page.locator('[data-action="leave-play"]').click();await page.waitForSelector('[data-mode="quick"]');await page.evaluate(async id=>{const db=await import('./js/db.js'),s=await db.get('sessions',id);await db.saveSession({...s,deadline:Date.now()-1000});},mockSession.sessionId);await nav('home');await page.locator(`[data-action="resume-session"][data-id="${mockSession.sessionId}"]`).click();await page.waitForSelector('.result-hero');assert.match(await page.locator('#app').innerText(),/模試の答え合わせ/);pass('mock uses A48 B12 and 120min; immediate grading hidden and expiry shows review');
 assert.deepEqual(errors,[]);writeFileSync('qa/browser-results.json',JSON.stringify({passed,errors},null,2));console.log(JSON.stringify({passed,errors},null,2));
}finally{await browser?.close();server.close();}
