await import(process.env.SG_FAKE_IDB_PATH||'fake-indexeddb/auto');
import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import*as db from'../public/js/db.js';import{CloudBackup}from'../public/js/cloud.js';import{DEFAULTS,APP_ID,UNKNOWN_OPTION_ID}from'../public/js/core.js';import{handleAPI,sha}from'../worker/api.js';import{createD1}from'./d1.mjs';
const key='e'.repeat(64),env={DB:createD1()},origin='https://sg-test.test';let cookie,failSave=false,editDuringSave=false;
await env.DB.prepare('INSERT INTO app_config(id,key_hash) VALUES(1,?)').bind(await sha(APP_ID+':'+key)).run();
globalThis.fetch=async(path,init={})=>{if(path.endsWith('/backups/save')&&failSave)return new Response(JSON.stringify({error:'test outage'}),{status:503});if(path.endsWith('/backups/save')&&editDuringSave){editDuringSave=false;await db.saveSettings({...DEFAULTS,bgm:.37});}const headers={...init.headers,Origin:origin,'CF-Connecting-IP':'cloud-test',...(cookie?{Cookie:cookie}:{})};const r=await handleAPI(new Request(origin+path,{...init,headers}),env);if(r.headers.has('Set-Cookie'))cookie=r.headers.get('Set-Cookie').split(';')[0];return r;};
const q=JSON.parse(readFileSync(new URL('../public/data/ipa-verified.json',import.meta.url))).questions[0];
await db.saveAnswer({attemptId:'cloud-first',questionId:q.questionId,revision:1,sessionId:'s',answeredAt:new Date().toISOString(),selectedOptionId:q.correctOptionId,correct:true,responseMs:1,topicTagsSnapshot:q.topicTags},{sessionId:'s',activeMs:1000});
const cloud=new CloudBackup();await cloud.login(key,'cloud integration test');
test('48-hour autosave persists dirty changes only; manual unchanged save adds no generation',async()=>{assert.equal(await cloud.save(true),true);const count=()=>env.DB.prepare('SELECT count(*) AS n FROM backups WHERE verified=1').first();assert.equal(await cloud.save(true),false);assert.equal((await count()).n,1);await db.saveSettings({...DEFAULTS,theme:'boss'});assert.equal(await cloud.save(false),false);await db.updateSync(s=>({...s,lastSuccess:Date.now()-48*3600000-1}));assert.equal(await cloud.save(false),true);assert.equal((await count()).n,2);});
test('failed request retains the exact pending snapshot and all local answers',async()=>{await db.saveSettings({...DEFAULTS,theme:'cyber'});failSave=true;await assert.rejects(cloud.save(true),/outage/);const before=await db.syncState();assert(before.pending);assert.equal((await db.all('attempts')).length,1);failSave=false;await db.saveSettings({...DEFAULTS,bgm:.25});assert.equal(await cloud.save(true),true);const after=await db.syncState();assert.equal(after.sentRevision,before.pending.revision);assert(after.revision>after.sentRevision);assert.equal(await cloud.save(true),true);});
test('an edit while uploading stays dirty until its own verified generation',async()=>{await db.saveSettings({...DEFAULTS,sfx:.12});editDuringSave=true;assert.equal(await cloud.save(true),true);let s=await db.syncState();assert(s.revision>s.sentRevision);assert.equal(await cloud.save(true),true);s=await db.syncState();assert.equal(s.revision,s.sentRevision);assert.equal((await env.DB.prepare('SELECT count(*) AS n FROM backups WHERE verified=1').first()).n,5);});
test('unknown response and custom quick size round-trip through authenticated cloud and safe restore',async()=>{
 const session={sessionId:'unknown-session',activeMs:0,learningTrack:'practical',topic:'暗号・ハッシュ'};await db.saveAnswer({attemptId:'cloud-unknown',questionId:q.questionId,revision:q.revision,sessionId:session.sessionId,answeredAt:new Date().toISOString(),selectedOptionId:UNKNOWN_OPTION_ID,correct:false,responseMs:1,topicTagsSnapshot:q.topicTags},session);
 await db.saveSettings({...await db.settings(),quickCount:3,quickTopic:'暗号・ハッシュ'});assert.equal(await cloud.save(true),true);
 const record=await env.DB.prepare('SELECT id,payload FROM backups WHERE verified=1 ORDER BY created_at DESC,id DESC LIMIT 1').first(),payload=JSON.parse(record.payload);assert.equal(payload.settings.quickCount,3);assert.equal(payload.settings.quickTopic,'暗号・ハッシュ');assert.equal(payload.sessions.find(s=>s.sessionId===session.sessionId).learningTrack,'practical');assert.equal(payload.attempts.find(a=>a.attemptId==='cloud-unknown').selectedOptionId,UNKNOWN_OPTION_ID);
 const expected=await db.all('attempts');await db.saveSettings({...await db.settings(),quickCount:20});await cloud.restore(record.id,(await db.syncState()).revision);assert.equal((await db.settings()).quickCount,3);assert.equal((await db.settings()).quickTopic,'暗号・ハッシュ');assert.deepEqual(await db.all('attempts'),expected);assert.equal((await db.all('safetyCopies')).at(-1).data.settings.quickCount,20);
});
