import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';
import {statistics,canonicalAttempts,rebuildReviews,selectQuestions,validatePack,validateBackup,backupDue,DEFAULTS,APP_ID,dayKey}from'../public/js/core.js';
const pack=JSON.parse(readFileSync(new URL('../public/data/ipa-verified.json',import.meta.url))),qs=pack.questions;
const attempt=(id,q,correct,time='2026-10-08T10:00:00Z')=>({attemptId:id,questionId:q.questionId,revision:q.revision,sessionId:'s',answeredAt:time,selectedOptionId:'ア',correct,firstAttempt:true,responseMs:123,topicTagsSnapshot:q.topicTags,combo:0});
test('seed bank includes only 22 verified official questions, all four explanations present',()=>{assert.equal(validatePack(pack).length,22);for(const q of qs){assert.equal(q.sourceType,'ipa_official');assert.equal(q.options.length,4);assert(!q.options.some(o=>o.text.includes('メ モ 用 紙')));}});
test('official answer sheets independently match every adopted answer',()=>{const answers={2026:'ウアアエウアエイイイアウ',2025:'エアイアイアエアエアイウ'};for(const q of qs)assert.equal(q.correctOptionId,answers[q.sourceYear][q.sourceNumber-1]);});
test('first wrong then correct preserves first accuracy and separates all-attempt accuracy',()=>{const a=[attempt('1',qs[0],false),attempt('2',qs[0],true,'2026-10-08T10:01:00Z')];const s=statistics(a);assert.equal(s.firstTotal,1);assert.equal(s.firstCorrect,0);assert.equal(s.total,2);assert.equal(s.correct,1);assert.deepEqual(canonicalAttempts(a).map(x=>x.firstAttempt),[true,false]);});
test('question display without an attempt remains unseen; initial challenge stops when exhausted',()=>{assert.equal(selectQuestions(qs,[],'first',100).length,22);const seen=qs.map((q,i)=>attempt(String(i),q,true));assert.equal(selectQuestions(qs,seen,'first').length,0);});
test('weakness selection prioritizes wrong questions, includes similar unseen and no duplicate IDs',()=>{const wrong=qs.slice(0,7).map((q,i)=>attempt(String(i),q,false)),selected=selectQuestions(qs,wrong,'weak',10,{},()=>.4);assert.equal(selected.length,10);assert.equal(new Set(selected.map(q=>q.questionId)).size,10);assert.equal(selected.filter(q=>wrong.some(a=>a.questionId===q.questionId)).length,7);});
test('review intervals increase after correct answers and reset after mistakes',()=>{const a=[attempt('1',qs[0],false),attempt('2',qs[0],true,'2026-10-09T10:00:00Z')];let r=rebuildReviews(a)[qs[0].questionId];assert.equal(r.stage,1);assert.equal(r.dueAt,'2026-10-12T10:00:00.000Z');r=rebuildReviews([...a,attempt('3',qs[0],false,'2026-10-10T10:00:00Z')])[qs[0].questionId];assert.equal(r.stage,0);assert.equal(r.dueAt,'2026-10-11T10:00:00.000Z');});
test('Tokyo date and Monday week aggregation agree around midnight',()=>{assert.equal(dayKey('2026-10-08T15:05:00Z'),'2026-10-09');const a=attempt('1',qs[0],true,'2026-10-04T16:00:00Z');assert.equal(statistics([a],[],'week').buckets[0].date,'2026-10-05');assert.equal(statistics([a],[],'month').buckets[0].date,'2026-10');});
test('XP has a per-question daily cap and remains deterministic',()=>{const a=Array.from({length:100},(_,i)=>attempt(String(i),qs[0],true));assert.equal(statistics(a).xp,36);assert.equal(statistics(a).level,1);});
test('48-hour backups require unsent changes, no changes creates no generation',()=>{assert.equal(backupDue({revision:2,sentRevision:1,lastSuccess:0},48*3600000-1),false);assert.equal(backupDue({revision:2,sentRevision:1,lastSuccess:0},48*3600000),true);assert.equal(backupDue({revision:2,sentRevision:2,lastSuccess:0},48*3600000),false);});
test('a mock is blocked without proper A48 B12 bank, selects real 60 when sufficient',()=>{assert.equal(selectQuestions(qs,[],'mock',60).length,0);const bank=Array.from({length:70},(_,i)=>({...qs[0],questionId:'mock-'+i,subject:i<48?'A':'B'}));const selected=selectQuestions(bank,[],'mock',60);assert.equal(selected.length,60);assert.equal(selected.filter(q=>q.subject==='A').length,48);assert.equal(selected.filter(q=>q.subject==='B').length,12);});
test('invalid or unverified packs never pass; changing answer requires a new ID',()=>{const bad=structuredClone(pack);bad.questions[0].verification.answerChecked=false;assert.throws(()=>validatePack(bad));const revision=structuredClone(pack);revision.questions[0].revision++;revision.questions[0].correctOptionId='ア';assert.throws(()=>validatePack(revision,qs));const duplicate=structuredClone(pack);duplicate.questions[1].questionId=duplicate.questions[0].questionId;assert.throws(()=>validatePack(duplicate));});
test('restore validates app, duplicate events and dangling sessions; settings are sanitized',()=>{const data={appId:APP_ID,formatVersion:1,attempts:[attempt('1',qs[0],true)],sessions:[{sessionId:'s',activeMs:1}],settings:{...DEFAULTS,bgm:8,recoveryKey:'should-not-persist'}};const result=validateBackup(data);assert.equal(result.settings.bgm,1);assert.equal(result.settings.recoveryKey,undefined);assert.throws(()=>validateBackup({...data,appId:'another-app'}));assert.throws(()=>validateBackup({...data,attempts:[...data.attempts,...data.attempts]}));assert.throws(()=>validateBackup({...data,sessions:[]}));});

test('period buckets retain unique problem count, cumulative level and configurable daily goal',()=>{const logs=Array.from({length:6},(_,i)=>({attemptId:'level-'+i,questionId:'level-q-'+i,answeredAt:'2026-10-09T00:00:00Z',correct:true,topicTagsSnapshot:['認証']}));const stats=statistics(logs,[],'day',5);assert.equal(stats.buckets[0].unique,6);assert.equal(stats.buckets[0].level,2);assert.equal(stats.goalDays,1);assert.equal(statistics(logs).goalDays,0);});

test('packs reject unsafe evidence links and incomplete source metadata',()=>{for(const change of [{verification:{...pack.questions[0].verification,evidenceUrl:'javascript:alert(1)'}},{difficulty:9},{sourceYear:null},{contentUpdatedAt:'invalid'}])assert.throws(()=>validatePack({...pack,questions:[{...pack.questions[0],...change}]}));});
test('speech preferences round-trip through backups and legacy backups get safe defaults',()=>{
 const data={appId:APP_ID,formatVersion:1,attempts:[],sessions:[],settings:{speechAuto:true,speechOptions:false,speechRate:1.3,speechVolume:.4,speechDuck:false}};
 const restored=validateBackup(data).settings;for(const [key,value]of Object.entries(data.settings))assert.equal(restored[key],value);
 const legacy=validateBackup({...data,settings:{bgm:.2}}).settings;assert.equal(legacy.speechAuto,false);assert.equal(legacy.speechOptions,true);assert.equal(legacy.bgm,.2);
 const invalid=validateBackup({...data,settings:{speechRate:100,speechVolume:8,speechAuto:'yes'}}).settings;assert.equal(invalid.speechRate,1);assert.equal(invalid.speechVolume,1);assert.equal(invalid.speechAuto,false);
});
