import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFileSync,mkdirSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {createD1} from './d1.mjs';
import {handleAPI} from '../worker/api.js';
import {securityHeaders} from '../worker/index.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.SG_PLAYWRIGHT_PATH||(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'));
const root=resolve('public'),env={DB:createD1()},official=JSON.parse(readFileSync('public/data/ipa-verified.json')).questions,practical=JSON.parse(readFileSync('public/data/practical-verified.json')).questions;
const server=createServer(async(req,res)=>{try{
 const origin=`http://127.0.0.1:${server.address().port}`,path=new URL(req.url,origin).pathname;
 if(path.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const r=await handleAPI(new Request(origin+req.url,{method:req.method,headers:req.headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})}),env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());return;}
 const file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root+'/'))throw Error('path');res.writeHead(200,{'Content-Type':{'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'}[extname(file)]||'text/plain',...securityHeaders});res.end(readFileSync(file));
}catch{res.writeHead(404).end('Not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const origin=`http://127.0.0.1:${server.address().port}`;
let browser;const errors=[],pass=label=>console.log('PASS',label);
try{
 browser=await chromium.launch({executablePath:process.env.SG_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--in-process-gpu']});
 const context=await browser.newContext({viewport:{width:360,height:800},isMobile:true,hasTouch:true});let hideNew=true;
 await context.route('**/data/practical*-verified.json',r=>hideNew?r.fulfill({status:404,body:'Not found'}):r.continue());
 await context.addInitScript(()=>Object.defineProperty(navigator,'share',{value:async data=>{window.qaShared=data;},configurable:true}));
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 const state=()=>page.evaluate(async()=>{const db=await import('./js/db.js');return {catalog:await db.all('questionCatalog'),attempts:await db.all('attempts'),sessions:await db.all('sessions'),prefs:await db.settings(),sync:await db.syncState(),tracks:await db.all('audioTracks')};});
 const nav=to=>page.locator(`#nav [data-view="${to}"]`).click();
 const finish=async()=>{await page.locator('[data-action="pause"]').click();await page.locator('[data-action="finish"]').click();await page.waitForSelector('.result-hero');};
 const home=async()=>{await page.locator('[data-action="nav"][data-view="home"]').first().click();await page.waitForSelector('#quick-count');};
 await page.goto(origin);await page.waitForSelector('#quick-topic');assert.equal((await state()).catalog.length,22);
 await page.evaluate(async()=>{const db=await import('./js/db.js'),{DEFAULTS,UNKNOWN_OPTION_ID}=await import('./js/core.js'),q=(await db.all('questionCatalog'))[0],prefs={...DEFAULTS,quickCount:3,autoNext:0};delete prefs.quickTopic;await db.saveSettings(prefs);await db.saveAnswer({attemptId:'old-answer',questionId:q.questionId,revision:1,sessionId:'old-session',answeredAt:'2026-10-08T00:00:00Z',selectedOptionId:UNKNOWN_OPTION_ID,correct:false,responseMs:100,topicTagsSnapshot:q.topicTags},{sessionId:'old-session',mode:'quick',activeMs:200,status:'complete',startedAt:'2026-10-08T00:00:00Z'});await db.addTrack({trackId:'existing-audio',name:'My BGM',size:4},new Blob(['wave']));});
 const before=await state();hideNew=false;await page.reload();await page.waitForSelector('#quick-topic');await page.waitForFunction(async()=>{const db=await import('./js/db.js');return (await db.all('questionCatalog')).length===86;});
 const updated=await state();assert.deepEqual(updated.attempts,before.attempts);assert.deepEqual(updated.sessions,before.sessions);assert.deepEqual(updated.sync,before.sync);assert.deepEqual(updated.tracks,before.tracks);assert.equal(updated.prefs.quickTopic,'');assert.equal(await page.evaluate(async()=>{const db=await import('./js/db.js');return (await db.get('audioBlobs','existing-audio')).blob.size;}),4);assert.equal(await page.locator('.practical-course').count(),8);assert.match(await page.locator('.practical-panel[data-set="1"]').innerText(),/32問/);assert.match(await page.locator('.hero').innerText(),/86問/);pass('real pack update adds 64 questions without changing legacy records, sessions, audio, sync or preferences');
 for(const [i,topic] of ['認証','暗号・ハッシュ','アクセス制御','脆弱性対策'].entries()){
  await page.locator(`.practical-course[data-topic="${topic}"]`).evaluate(el=>{el.click();el.click();});await page.waitForSelector('.option');const active=(await state()).sessions.find(s=>s.status==='active');assert.equal(active.learningTrack,'practical');assert.equal(active.topic,topic);assert.equal(active.questionIds.length,3);assert(active.questionIds.every(id=>practical.find(q=>q.questionId===id)?.topicTags.includes(topic)));
  assert.equal(await page.locator('#question-stem').innerText(),practical.find(q=>q.topicTags.includes(topic)&&q.learningOrder===1).stem);assert.match(await page.locator('.question-meta').innerText(),/入門.*非公式/);assert.equal((await state()).sessions.filter(s=>s.status==='active').length,1);
  await finish();await home();
 }pass('all four fields start three introductory questions in basic order and suppress double starts');
 await page.locator('.practical-course[data-topic="暗号・ハッシュ"]').click();await page.waitForSelector('.option');const hashQ=practical.find(q=>q.concept==='ハッシュ値');assert.equal(await page.locator('#question-stem').innerText(),hashQ.stem);await page.locator('[data-action="unknown"]').click();await page.waitForSelector('.explanation');assert.match(await page.locator('.explanation').innerText(),/指紋/);await page.locator('[data-action="ai-question"]').click();assert((await page.evaluate(()=>qaShared.text)).includes(hashQ.stem));assert((await page.evaluate(()=>qaShared.text)).includes('分からない'));await page.locator('[data-action="next"]').click();await page.waitForFunction(old=>document.querySelector('#question-stem').textContent!==old,hashQ.stem);
 await page.locator('[data-action="pause"]').click();await page.locator('[data-action="leave-play"]').click();const interrupted=(await state()).sessions.find(s=>s.status==='interrupted');assert(interrupted);await page.reload();await page.waitForSelector('[data-action="resume-session"]');await page.locator('[data-action="resume-session"]').click();await page.waitForSelector('.option');assert.equal(await page.locator('#question-stem').innerText(),practical.find(q=>q.questionId===interrupted.questionIds[1]).stem);await finish();assert.equal(await page.locator('.mistake-item').count(),1);pass('hash question saves unknown, exports full AI context, preserves course after reload and lists it at the end');
 await home();await page.locator('#quick-topic').selectOption('暗号・ハッシュ');await page.locator('#quick-count').fill('100');await page.locator('[data-action="start"][data-mode="quick"]').click();await page.waitForSelector('.option');const scoped=(await state()).sessions.find(s=>s.status==='active');assert.equal(scoped.topic,'暗号・ハッシュ');assert.equal(scoped.questionIds.length,8);assert(scoped.questionIds.every(id=>practical.find(q=>q.questionId===id)?.topicTags.includes('暗号・ハッシュ')));await finish();await home();await page.reload();await page.waitForSelector('#quick-topic');assert.equal(await page.locator('#quick-topic').inputValue(),'暗号・ハッシュ');pass('ordinary quick start filters the chosen field, caps to inventory and persists field across reload');
 const stats=await page.evaluate(async()=>{const db=await import('./js/db.js'),{statistics}=await import('./js/core.js');return statistics(await db.all('attempts'));});assert.equal(stats.total,2);assert.equal(stats.firstTotal,2);assert.equal(stats.firstCorrect,0);
 await nav('library');await page.locator('#library-tag').selectOption('暗号・ハッシュ');assert.equal(await page.locator('.library-item').count(),8);await page.locator('.library-item').first().evaluate(el=>el.open=true);assert.match(await page.locator('.library-item').first().innerText(),/非公式/);assert.match(await page.locator('.library-item').first().innerText(),/SGとのつながり/);await nav('home');await page.locator('[data-mode="mock"]').click();await page.waitForSelector('#modal[open]');assert.match(await page.locator('#modal-content').innerText(),/A 22問／B 0問/);await page.locator('#modal-close').click();pass('library identifies original questions and sources; first accuracy stays immutable; beginners do not enable mock exams');
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await page.waitForFunction(async()=>{const c=await caches.open('sg-study-deck-v1.5.0');return !!(await c.match('./data/practical-verified.json'));});await context.unroute('**/data/practical*-verified.json');await context.setOffline(true);await page.reload();await page.waitForSelector('#quick-topic');await page.locator('#quick-count').fill('1');await page.locator('.practical-course[data-topic="アクセス制御"]').click();await page.waitForSelector('.option');assert.match(await page.locator('.question-meta').innerText(),/入門/);await page.locator('[data-action="unknown"]').click();await page.waitForSelector('.explanation');assert.equal((await state()).attempts.length,3);await page.locator('[data-action="next"]').click();await page.waitForSelector('.result-hero');await home();pass('new data and module are cached; offline course starts and saves a new answer');
 await context.setOffline(false);
 for(const theme of ['neon','boss','cyber']){await page.locator(`[data-action="theme"][data-theme="${theme}"]`).click();await page.waitForSelector(`[data-action="theme"][data-theme="${theme}"][aria-pressed="true"]`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const heights=await page.locator('.practical-course').evaluateAll(boxes=>boxes.map(box=>box.getBoundingClientRect().height));assert.equal(heights.length,8);assert(heights.every(height=>height>=44));}
 mkdirSync('qa',{recursive:true});await page.locator('.practical-panel[data-set="1"]').screenshot({path:'qa/practical-mobile.png',animations:'disabled',timeout:45000});assert.deepEqual(errors,[]);pass('eight cards remain readable in all themes at 360px with sufficient tap areas and no script errors');
}finally{await browser?.close();server.close();}
