import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFileSync,mkdirSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
import {createD1} from './d1.mjs';
import {handleAPI} from '../worker/api.js';
import {securityHeaders} from '../worker/index.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.SG_PLAYWRIGHT_PATH||(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright'));
const root=resolve('public'),env={DB:createD1()},official=JSON.parse(readFileSync('public/data/ipa-verified.json')).questions,first=JSON.parse(readFileSync('public/data/practical-verified.json')).questions,practical=JSON.parse(readFileSync('public/data/practical2-verified.json')).questions;
const server=createServer(async(req,res)=>{try{
 const origin=`http://127.0.0.1:${server.address().port}`,path=new URL(req.url,origin).pathname;
 if(path.startsWith('/api/')){const chunks=[];for await(const c of req)chunks.push(c);const r=await handleAPI(new Request(origin+req.url,{method:req.method,headers:req.headers,...(chunks.length?{body:Buffer.concat(chunks)}:{})}),env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());return;}
 const file=resolve(root,'.'+(path==='/'?'/index.html':path));if(!file.startsWith(root+'/'))throw Error('path');res.writeHead(200,{'Content-Type':{'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png'}[extname(file)]||'text/plain',...securityHeaders});res.end(readFileSync(file));
}catch{res.writeHead(404).end('Not found');}});
await new Promise(done=>server.listen(0,'127.0.0.1',done));const origin=`http://127.0.0.1:${server.address().port}`;
let browser;const errors=[],pass=label=>console.log('PASS',label);
try{
 browser=await chromium.launch({executablePath:process.env.SG_CHROMIUM_PATH,args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--in-process-gpu']});
 const context=await browser.newContext({viewport:{width:360,height:800},isMobile:true,hasTouch:true});let hideNew=true;
 await context.route('**/data/practical2-verified.json',r=>hideNew?r.fulfill({status:404,body:'Not found'}):r.continue());
 await context.addInitScript(()=>Object.defineProperty(navigator,'share',{value:async data=>{window.qaShared={...data,active:navigator.userActivation.isActive};},configurable:true}));
 const page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 const state=()=>page.evaluate(async()=>{const db=await import('./js/db.js');return {catalog:await db.all('questionCatalog'),attempts:await db.all('attempts'),sessions:await db.all('sessions'),prefs:await db.settings(),sync:await db.syncState(),tracks:await db.all('audioTracks')};});
 const home=async()=>{await page.locator('[data-action="nav"][data-view="home"]').first().click();await page.waitForSelector('#quick-count');};
 const finish=async()=>{await page.locator('[data-action="pause"]').click();await page.locator('[data-action="finish"]').click();await page.waitForSelector('.result-hero');};
 await page.goto(origin,{waitUntil:'domcontentloaded'});await page.waitForSelector('#quick-count');assert.equal((await state()).catalog.length,54);
 await page.evaluate(async()=>{const db=await import('./js/db.js'),{DEFAULTS,UNKNOWN_OPTION_ID}=await import('./js/core.js'),q=(await db.all('questionCatalog')).find(q=>q.learningTrack==='practical');await db.saveSettings({...DEFAULTS,autoNext:0,quickCount:3});await db.saveAnswer({attemptId:'legacy',questionId:q.questionId,revision:1,sessionId:'legacy',answeredAt:'2026-10-08T00:00:00Z',selectedOptionId:UNKNOWN_OPTION_ID,correct:false,responseMs:200,topicTagsSnapshot:q.topicTags},{sessionId:'legacy',mode:'quick',learningTrack:'practical',topic:q.topicTags[0],activeMs:200,status:'complete',startedAt:'2026-10-08T00:00:00Z'});await db.addTrack({trackId:'legacy-music',name:'My BGM',size:4},new Blob(['wave']));});
 const before=await state();hideNew=false;await page.reload({waitUntil:'domcontentloaded',timeout:45000});await page.waitForSelector('#quick-count');await page.waitForFunction(async()=>{const d=await import('./js/db.js');return (await d.all('questionCatalog')).length===86;});const after=await state();
 for(const key of ['attempts','sessions','prefs','sync','tracks'])assert.deepEqual(after[key],before[key]);assert.equal(await page.evaluate(async()=>{const d=await import('./js/db.js');return (await d.get('audioBlobs','legacy-music')).blob.size;}),4);assert.equal(await page.locator('.practical-panel[data-set="2"] .practical-course').count(),4);pass('54-to-86 real update preserves existing practical history, settings, sessions, music and backup revisions');
 const topics=['ネット・ブラウザ','詐欺・危険ファイル','クラウド・AI','トラブル初動'];
 for(const [i,topic] of topics.entries()){
  await page.locator(`[data-action="theme"][data-theme="${['neon','boss','cyber','neon'][i]}"]`).click();await page.locator(`.practical-course[data-topic="${topic}"]`).click();await page.waitForSelector('.option');
  const s=(await state()).sessions.find(s=>s.status==='active');assert.equal(s.practicalSet,2);assert.equal(s.questionIds.length,3);assert(s.questionIds.every(id=>practical.some(q=>q.questionId===id&&q.topicTags.includes(topic))));assert.equal(await page.locator('#question-stem').innerText(),practical.find(q=>q.topicTags.includes(topic)&&q.learningOrder===1).stem);assert.match(await page.locator('.question-meta').innerText(),/実用入門②/);assert.equal(await page.locator('.term-notes').count(),0);await finish();await home();
 }pass('four second-stage courses work in all themes and leave term explanations until after the answer');
 await page.locator('.practical-panel[data-set="2"] [data-topic=""]').click();await page.waitForSelector('.option');let s=(await state()).sessions.find(s=>s.status==='active');assert.equal(s.topic,'');assert.equal(s.practicalSet,2);assert(s.questionIds.every(id=>id.startsWith('sg-practical2-')));await finish();await page.locator('[data-action="start"]').click();await page.waitForSelector('.option');s=(await state()).sessions.find(s=>s.status==='active');assert.equal(s.practicalSet,2);assert(s.questionIds.every(id=>id.startsWith('sg-practical2-')));await finish();await home();await page.locator('.practical-panel[data-set="1"] [data-topic=""]').click();await page.waitForSelector('.option');assert((await state()).sessions.find(s=>s.status==='active').questionIds.every(id=>first.some(q=>q.questionId===id)));await finish();await home();pass('mix and result replay retain the selected stage, and first-stage mix excludes set 2');
 await page.locator('.practical-course[data-topic="ネット・ブラウザ"]').click();await page.waitForSelector('.option');const q=practical[0];assert.equal(await page.locator('#question-stem').innerText(),q.stem);await page.locator('[data-action="unknown"]').click();await page.waitForSelector('.term-notes');for(const t of q.termNotes){assert((await page.locator('.term-notes').innerText()).includes(t.term));assert((await page.locator('.term-notes').innerText()).includes(t.meaning));}await page.locator('[data-action="ai-question"]').click();const shared=await page.evaluate(()=>qaShared);assert.equal(shared.active,true);assert(shared.text.includes('【用語メモ】'));assert(shared.text.includes('TLS：'));assert(shared.text.includes('分からない'));await page.locator('[data-action="next"]').click();await page.waitForFunction(old=>document.querySelector('#question-stem').textContent!==old,q.stem);await page.locator('[data-action="pause"]').click();await page.locator('[data-action="leave-play"]').click();const interrupted=(await state()).sessions.find(s=>s.status==='interrupted');await page.reload({waitUntil:'domcontentloaded',timeout:45000});await page.waitForSelector('[data-action="resume-session"]');await page.locator('[data-action="resume-session"]').click();await page.waitForSelector('.option');assert.equal((await state()).sessions.find(s=>s.status==='active').practicalSet,2);assert.equal(await page.locator('#question-stem').innerText(),practical.find(q=>q.questionId===interrupted.questionIds[1]).stem);await finish();await page.locator('.mistake-item').evaluate(el=>el.open=true);assert.match(await page.locator('.mistake-item .term-notes').innerText(),/TLS/);await page.locator('[data-action="ai-mistakes"]').click();assert((await page.evaluate(()=>qaShared.text)).includes('【用語メモ】'));await home();pass('unknown saves immediately; glossary reaches direct and batch AI sharing, final list and resumed stage');
 await page.locator('#quick-count').fill('100');await page.locator('#quick-topic').selectOption('クラウド・AI');await page.locator('[data-mode="quick"]').click();await page.waitForSelector('.option');s=(await state()).sessions.find(s=>s.status==='active');assert.equal(s.questionIds.length,8);assert(s.questionIds.every(id=>practical.some(q=>q.questionId===id&&q.topicTags.includes('クラウド・AI'))));await finish();await home();pass('ordinary quick start can select a second-stage field and caps to its eight questions');
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await page.waitForFunction(async()=>{const c=await caches.open('sg-study-deck-v1.5.0');return !!(await c.match('./data/practical2-verified.json'));});await context.unroute('**/data/practical2-verified.json');await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded',timeout:45000});await page.waitForSelector('#quick-count');await page.locator('#quick-count').fill('1');await page.locator('.practical-course[data-topic="クラウド・AI"]').click();await page.waitForSelector('.option');await page.locator('[data-action="unknown"]').click();await page.waitForSelector('.term-notes');await page.locator('[data-action="next"]').click();await page.waitForSelector('.result-hero');await home();assert.equal((await state()).attempts.length,3);await page.reload({waitUntil:'domcontentloaded',timeout:45000});await page.waitForSelector('#quick-count');assert.equal((await state()).attempts.length,3);pass('set-2 JSON and glossary operate offline with IndexedDB answers retained after reload');
 await page.locator('#nav [data-view="library"]').click();await page.locator('#library-tag').selectOption('クラウド・AI');assert.equal(await page.locator('.library-item').count(),8);await page.locator('.library-item').first().evaluate(el=>el.open=true);assert.equal(await page.locator('.term-notes').count(),8);await home();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);for(const b of await page.locator('.practical-course').all())assert((await b.boundingBox()).height>=44);
 mkdirSync('qa',{recursive:true});await page.locator('.practical-panel[data-set="2"]').screenshot({path:'qa/practical2-mobile.png',animations:'disabled',timeout:45000});assert.deepEqual(errors,[]);pass('library exposes vocabulary; mobile cards fit 360px with adequate tap areas and no script errors');
}finally{await browser?.close();server.close();}
