// Private deployment verification. Supply a key file; never embed its contents.
import{createRequire}from'node:module';import{readFileSync,writeFileSync}from'node:fs';import assert from'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.SG_PLAYWRIGHT_PATH||(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright')),root='https://sg-study-deck.dengana-10011212.workers.dev',key=readFileSync(process.env.SG_RECOVERY_KEY_FILE,'utf8').split('\n')[2],bank=JSON.parse(readFileSync('public/data/ipa-verified.json'));
const proxyURL=process.env.HTTPS_PROXY||process.env.HTTP_PROXY;const proxy=proxyURL?(()=>{const u=new URL(proxyURL);return{server:u.protocol+'//'+u.host,...(u.username?{username:decodeURIComponent(u.username),password:decodeURIComponent(u.password)}:{})};})():undefined;
const browser=await chromium.launch({...(process.env.SG_CHROMIUM_PATH?{executablePath:process.env.SG_CHROMIUM_PATH}:{}),...(proxy?{proxy}:{}),args:['--no-sandbox','--no-zygote','--single-process','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--in-process-gpu']});
const passed=[],errors=[];const pass=s=>{passed.push(s);console.log('PASS',s);};
try{
 // The managed QA proxy CA is not in this temporary Chromium image. HTTPS is independently verified by urllib with certificate verification enabled.
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,ignoreHTTPSErrors:!!proxy,userAgent:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36'}),page=await context.newPage();page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));
 const statusReady=page.waitForResponse(r=>r.url()===root+'/api/status');const response=await page.goto(root,{waitUntil:'domcontentloaded',timeout:45000});assert.equal(response.status(),200);await page.waitForSelector('[data-mode="quick"]');await statusReady;await page.screenshot({path:'qa/production-home-mobile.png'});pass('Final deployed app boots in a mobile Chromium browser');
 await page.locator('[data-mode="quick"]').first().click();await page.waitForSelector('.option');const stem=await page.locator('#question-stem').innerText(),question=bank.questions.find(q=>q.stem===stem);await page.locator(`[data-option="${question.correctOptionId}"]`).click();await page.waitForSelector('[data-action="show-explanation"]');await page.locator('[data-action="pause"]').click();await page.locator('[data-action="finish"]').click();await page.waitForSelector('.result-hero');pass('Live theme, answer effects and immediate IndexedDB saving work');
 await page.locator('#nav [data-view="settings"]').click();await page.waitForSelector('#recovery-key');await page.evaluate(secret=>{document.querySelector('#recovery-key').value=secret;document.querySelector('#device-name').value='SG UI deployment QA 20261009';},key);await page.locator('[data-action="cloud-login"]').click();await page.waitForSelector('[data-action="cloud-logout"]');const deviceId=await page.evaluate(async()=>{const {api}=await import('./js/cloud.js');return(await api('status')).deviceId;});await page.locator('[data-action="cloud-save"]').click();await page.waitForFunction(()=>document.querySelector('#cloud-status')?.textContent==='クラウド保存済み');const backupIds=await page.evaluate(async()=>{const {api}=await import('./js/cloud.js');return(await api('backups')).backups.map(x=>x.id);});assert.equal(backupIds.length,1);pass('Live browser Secure HttpOnly cookie saves to real D1');
 await page.locator('[data-action="cloud-history"]').click();await page.waitForSelector('[data-action="cloud-restore"]');await page.locator('[data-action="cloud-restore"]').first().click();await page.waitForSelector('[data-action="confirm-restore"]');await page.locator('[data-action="confirm-restore"]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);const restored=await page.evaluate(async()=>{const db=await import('./js/db.js');return{answers:(await db.all('attempts')).length,safety:(await db.all('safetyCopies')).length};});assert.equal(restored.answers,1);assert.equal(restored.safety,1);pass('Live D1 restore via confirmation UI retains the old study record in a safety copy');
 await page.locator('[data-action="cloud-logout"]').click();await page.waitForSelector('#recovery-key');pass('Live browser logout revokes its device');assert.deepEqual(errors,[]);writeFileSync('qa/production-browser-results.json',JSON.stringify({passed,errors,qaBackupIds:backupIds,qaDeviceId:deviceId},null,2));
}finally{await browser.close();}
