import test from'node:test';import assert from'node:assert/strict';import{handleAPI,sha,COOKIE}from'../worker/api.js';import{createD1}from'./d1.mjs';import{APP_ID,DEFAULTS}from'../public/js/core.js';
const key='a'.repeat(64),env={DB:createD1()},url='https://sg-study-deck.test';let token;
async function req(path,data,cookie=token,origin=url,ip='127.0.0.1'){const headers={Origin:origin,'CF-Connecting-IP':ip};if(cookie)headers.Cookie=cookie;if(data)headers['Content-Type']='application/json';return handleAPI(new Request(url+'/api/'+path,{method:data?'POST':'GET',headers,body:data?JSON.stringify(data):undefined}),env);}
const payload=i=>JSON.stringify({appId:APP_ID,formatVersion:1,exportedAt:'2026-10-09T00:00:00Z',attempts:[{attemptId:'a'+i,questionId:'q',revision:1,sessionId:'s',answeredAt:'2026-10-09T00:00:00Z',selectedOptionId:'ア',correct:true,responseMs:1,topicTagsSnapshot:['認証']}],sessions:[{sessionId:'s',activeMs:1}],settings:DEFAULTS});
await env.DB.prepare('INSERT INTO app_config(id,key_hash) VALUES(1,?)').bind(await sha(APP_ID+':'+key)).run();
test('all records and management reject unauthenticated access; hostile origin rejected',async()=>{for(const p of ['status','backups','backups/'+crypto.randomUUID(),'devices'])assert.equal((await req(p,undefined,null)).status,401);assert.equal((await req('login',{key},null,'https://attacker.test')).status,403);assert.equal((await req('backups/save',{},null)).status,401);assert.equal((await req('login',{key:'b'.repeat(64)},null)).status,401);});
test('login issues an app-specific HttpOnly Secure SameSite cookie; no raw token in D1',async()=>{const r=await req('login',{key,name:'Unit test'},null);assert.equal(r.status,200);const value=r.headers.get('set-cookie');assert.match(value,/HttpOnly/);assert.match(value,/Secure/);assert.match(value,/SameSite=Strict/);token=value.split(';')[0];const devices=await env.DB.prepare('SELECT * FROM devices').all();assert(!JSON.stringify(devices).includes(token.split('=')[1]));assert.equal((await req('status')).status,200);assert.equal((await req('status',undefined,'__Host-other-app='+token.split('=')[1])).status,401);});
let latest=null,operation,firstId;
test('save/read/confirm verifies full payload and retains newest five; repeat is idempotent',async()=>{for(let i=0;i<7;i++){const text=payload(i),op=crypto.randomUUID(),body={payload:text,checksum:await sha(text),operationId:op,baseId:latest};const r=await req('backups/save',body);assert.equal(r.status,200,await r.clone().text());const {id}=await r.json();if(i===0){firstId=id;operation=body;}const repeat=await req('backups/save',body);assert.equal((await repeat.json()).id,id);const read=await req('backups/'+id);assert.equal((await read.json()).payload,text);const before=(await(await req('backups')).json()).backups.length;await req('backups/confirm',{id,checksum:body.checksum});latest=id;const list=(await(await req('backups')).json()).backups;assert.equal(list.length,Math.min(i+1,5));assert(list.some(x=>x.id===id));}});
test('corrupt/failed backup never prunes normal five and detects stale device changes',async()=>{const before=(await(await req('backups')).json()).backups;assert.equal((await req('backups/save',{operationId:crypto.randomUUID(),payload:payload(8),checksum:'broken',baseId:latest})).status,400);assert.equal((await req('backups/save',{operationId:crypto.randomUUID(),payload:payload(8),checksum:await sha(payload(8)),baseId:'stale'})).status,409);assert.deepEqual((await(await req('backups')).json()).backups,before);});
test('unfinished uploads do not block devices; exactly one conflicting confirmation wins',async()=>{const checksum=await sha(payload(9)),a={operationId:crypto.randomUUID(),payload:payload(9),checksum,baseId:latest},b={...a,operationId:crypto.randomUUID()};const first=await(await req('backups/save',a)).json(),second=await(await req('backups/save',b)).json();assert(first.id&&second.id);assert.equal((await req('backups/confirm',{id:second.id,checksum})).status,200);assert.equal((await req('backups/confirm',{id:first.id,checksum})).status,409);assert.equal((await req('backups/confirm',{id:second.id,checksum})).status,200);latest=second.id;assert.equal((await(await req('backups')).json()).backups.length,5);});
test('revocation requires recovery key and invalidates device immediately; key rotation revokes all',async()=>{const device=(await(await req('status')).json()).deviceId;assert.equal((await req('devices/revoke',{id:device})).status,401);assert.equal((await req('devices/revoke',{id:device,key})).status,200);assert.equal((await req('status')).status,401);const login=await req('login',{key},null);token=login.headers.get('set-cookie').split(';')[0];assert.equal((await req('key/rotate',{key,newKey:'c'.repeat(64)})).status,200);assert.equal((await req('status')).status,401);assert.equal((await req('login',{key},null,url,'rotate-test')).status,401);assert.equal((await req('login',{key:'c'.repeat(64)},null,url,'rotate-test')).status,200);});
test('rate limiting persists in database and blocks the ninth authentication attempt',async()=>{for(let i=0;i<8;i++)assert.equal((await req('login',{key:'invalid'},null,url,'rate-test')).status,401);assert.equal((await req('login',{key:'invalid'},null,url,'rate-test')).status,429);});
