CREATE TABLE IF NOT EXISTS app_config (id INTEGER PRIMARY KEY CHECK(id=1), key_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS devices (id TEXT PRIMARY KEY, token_hash TEXT UNIQUE NOT NULL, name TEXT NOT NULL, created_at TEXT NOT NULL, last_seen TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS backups (id TEXT PRIMARY KEY, operation_id TEXT UNIQUE NOT NULL, created_at TEXT NOT NULL, payload TEXT NOT NULL, checksum TEXT NOT NULL, attempts INTEGER NOT NULL, sessions INTEGER NOT NULL, verified INTEGER NOT NULL DEFAULT 0, device_id TEXT NOT NULL, base_id TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS backup_created ON backups(created_at DESC);
CREATE TABLE IF NOT EXISTS auth_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);
